tensorflow/community

rfcs/20180604-dynamic-kernels.md

Please leave comments to this PR. Comment period will be open until 2018-06-19
cc @ewilderj @martinwicke 
| Status | Proposed |
:-------------- | :-------------------------------------------------|
| **Author(s)** | Gunhan Gulsoy (Google) |
| **Sponsor**   | Martin Wicke (Google)  |
| **Updated**   | 2018-06-04             |
This document describes a new way to create and deploy new kernels for
TensorFlow. We propose deploying kernels in separate shared libraries (dso,
dylib or dll) and loading these at runtime. While at the moment the scope of
this document only covers **TensorFlow Python distribution**, we aim to
generalize this approach for all TF distributions. With this mechanism, we
would like to create the following capabilities:
* Loading kernels dynamically at runtime from shared …

TF Dynamic kernel design.

---

rfcs/yyyymmdd-rfc-template.md

The ID is actually the filename of the markdown doc, so no need for ID.

Remove redundant ID header from RFC template

---

rfcs/20180626-tensor-forest.md

Since tree algorithm is one of the most popular algorithm used in kaggle competition
and we already have a contrib project [tensor_forest](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tensor_forest) and people like them. If would be beneficial to move them inside of canned estimators.
cc: @nataliaponomareva

RFC: Add TensorForest classifier and regressor to canned estimators

---

rfcs/20180731-dockerfile-assembler.md

**Review is now closed for comments**
| Status        | Accepted       |
| **Author(s)** | Austin Anderson (angerson@google.com)
| **Sponsor**   | Gunhan Gulsoy (gunan@google.com)                     |
| **Updated**   | 2018-07-31                                           |
This document describes a new way to manage TensorFlow's dockerfiles. Instead of handling complexity via an on-demand build script, Dockerfile maintainers manage re-usable chunks called partials which are assembled into documented, standard, committed-to-repo Dockerfiles that don't need extra scripts to build. It is also decoupled from the system that builds and uploads the Docker images, which can be safely handled by separate CI scripts. …

RFC: TensorFlow Dockerfile Assembler

---

rfcs/20180726-tf-data-windowing-reducers.md

**This RFC will be open for comment until Friday, August 10th, 2018.**
cc @jsimsa @mrry
:---------------|:-----------------------------------------------------|
| **Author(s)** | Jiri Simsa (Google)                                  |
| **Sponsor**   | Derek Murray (Google)                                |
| **Updated**   | 2018-07-26                                           |
This proposal addresses the known limitations of the current tf.data batching API:
*   it provides a mechanism for padded batching of sparse tensors
*   it facilitates customization of batching logic (users can now express batching logic as a pure Python function)
*   it enables application of different batching logic on different components

RFC: Generalizing tf.data batching using windowing and reducers

---

governance/SIGS.md

Regularize language so 'SIG lead' is the unique term for a group lead.

Clarify language regarding SIG leads

---

rfcs/20180827-api-names.md

**Review open for comments until 2018-09-11**
| Status        | Accepted       |
| **Author(s)** | Anna Revinskaya (annarev@google.com), Andrew Selle (aselle@google.com) |
| **Sponsor**   | Martin Wicke (wicke@google.com)                      |
| **Updated**   | 2018-08-27                                           |
This document proposes organizing TensorFlow API symbols in corresponding logical subnamespaces. As TensorFlow library grows, it is important to structure namespaces in a clear way for easier discoverability and usability.
We define **endpoint** as full name that can be used to access a TensorFlow
symbol. For e.g. [name_scope](https://www.tensorflow.org/api_docs/python/tf/name_scope) can be accessed using …

RFC: TensorFlow API symbols and namespaces

---

rfcs/20180920-unify-rnn-interface.md

**Review period open until 2018-09-10**
| ------------- |:---------------------------------------------------- |
| **Author(s)** | Scott Zhu (scottzhu@google.com)                       |
| **Sponsor**   | Eugene Brevdo (ebrevdo@google.com), Patrick Nguyen (drpng@google.com)|
| **Updated**   | 2018-08-24                                           |
Unify RNN (LSTM/GRU/other recurrent models) interfaces between TF RNN and Keras RNN at the release 
of TensorFlow 2.0.

RFC: Unify RNN interface

---

rfcs/20181016-replicator.md

Review period closes 2018-11-08
| Status        | Proposed                                                                  |
| :------------ | :------------------------------------------------------------------------ |
| **Author(s)** | cjfj@google.com, dominikg@google.com, jhseu@google.com, joshl@google.com, |
|               | petebu@google.com, priyag@google.com, tomhennigan@google.com              |
| **Sponsor**   | wicke@google.com                                                          |
| **Updated**   | 2018-11-12                                                                |
This document presents a proposal to seek feedback on a revised [Distribution Strategy](https://www.tensorflow.org/api_docs/python/tf/contrib/distribute/DistributionStrategy) API and illustrate its usage …

RFC: Distribution Strategy - Revised API

---

rfcs/20180918-functions-not-sessions-20.md

**Review period closes 2018-10-04**
| **Author(s)** | ashankar@google.com, joshl@google.com                |
| **Sponsor**   | apassos@google.com                                   |
| **Updated**   | 2018-09-18                                           |
Proposal to make TensorFlow be more "Pythonic" in 2.0. In four bullet points:
- Encourage the encapsulation of graph computation as Python functions 
(where the graph is executed when the function is invoked, instead of via Session)
- Align "state" in the TensorFlow runtime (e.g., resource tensors like those that back tf.Variable objects) with state in the Python program (e.g., Python objects corresponding to the runtime state with …

RFC: Functions, not sessions in 2.0

---

rfcs/20181016-optimizer-unification.md

The feedback phase will be open for two weeks until 2018-10-30.
| **Author(s)** | Francois Chollet (fchollet@google.com)               |
| **Sponsor**   | Martin Wicke (wicke@google.com)                      |
| **Updated**   | 2018-10-16                                           |
Keras has its own set of optimizers, living in `tf.keras.optimizers`. TensorFlow has also its own set of optimizers, living in `tf.train`.
We will merge them into a single set of optimizers, which will be based on the existing TensorFlow optimizers, but with some added features. These optimizers will replace the Keras optimizers. In the process, there will be some signature changes.
This RFC describes all …

RFC: Optimizer unification in TensorFlow 2.0

---

rfcs/20181025-tf-integration-testing.md

**The feedback phase will be open for 2 weeks until 2018-11-09.**
| Status        | Proposed                                                |
| **Author**    | amitpatankar@google.com 								  |
| **Sponsor**   | gunan@google.com                                        |
| **Updated**   | 2018-10-24                                              |
With TensorFlow becoming more and more modularized, libraries that sit on top of core TensorFlow need to be tested. Unfortunately we cannot wait for any adjustments made to core TensorFlow to propagate through to a formal release and we need a way to have a reliable way of getting the latest stable TensorFlow to test any new changes to the external repositories.

RFC: TensorFlow Integration Testing

---

sigs/io/CHARTER.md
sigs/io/RELEASE.md

This fix update the SIG IO's release process so that
anyone could help the release for SIG IO.

Add SIG IO release process and release team

---

rfcs/20180907-contrib-sunset.md

**The feedback phase will be open for four weeks until 2018-10-01.**
| Status        | *Proposed*                                           |
| **Author(s)** | Martin Wicke (wicke@tensorflow.org)                  |
| **Sponsor**   | Edd Wilder-James (ewj@tensorflow.org)                |
| **Updated**   | 2018-09-07                                           |
The `tf.contrib` module plays several important roles in the TensorFlow
ecosystem: It has made it easy for members of the community to contribute to
TensorFlow, and have their contributions tested and maintained. It is also used
as a staging ground to test early-stage and experimental features in TensorFlow.
However, as the community has grown, the lack of …

RFC: Sunset tf.contrib

---

sigs/io/RELEASE.md

This PR adds Anthony to the Release team of sig-io with his PyPI.org.
/cc @dmitrievanthony @ewilderj 

Add Anthony to the Release team of sig-io

---

sigs/io/RELEASE.md

Added the check list and instructions to release tensorflow/io R package to CRAN.

Add tensorflow/io R Package CRAN release instructions

---

rfcs/20181214-move-to-addons.md

**The feedback phase will be open for four weeks until 2019-01-14**
| Status        | Accepted       |
| **Author(s)** | Sean Morgan (seanmorgan@outlook.com), Armando Fandango (armando@neurasights.com) |
| **Sponsor**   | Karmel Allison (karmel@google.com)                 |
| **Updated**   | 2018-12-16       
With the upcoming removal of tf.contrib in TF 2.0, we are in the process
of deciding what existing functionality will be moved and maintained in
the [tensorflow/addons](https://github.com/tensorflow/addons) repository.
This document details what functionality the SIG plans to move and
invites discussion around the decisions.

RFC: Move from tf.contrib to addons

---

rfcs/20181217-tf2-random-numbers.md

**The feedback phase will be open for four weeks until 2019-01-14**
| Status        | Accepted       |
| **Author(s)** | Peng Wang (wangpeng@google.com), Josh Levenberg (joshl@google.com), Alexandre Passos (apassos@google.com), Asim Shankar (ashankar@google.com) |
| **Sponsor**   | Josh Levenberg (joshl@google.com), Alexandre Passos (apassos@google.com) |
| **Updated**   | 2019-01-30 |      
This document proposes new stateful random-number ops that rely on resource variables to manage states, and addition of support of multiple RNG algorithms and batch seeds.

RFC: Random numbers in TensorFlow 2.0

---

sigs/io/RELEASE.md

This change adds Bryan to the SIG-IO release team with GitHub and PyPi handles.

Add Bryan to SIG-IO release team

---

rfcs/20190116-embedding-partitioned-variable.md

**Review period will close at the end of 2019-01-30**
| Status        | Accepted                                                                  |
| :------------ | :------------------------------------------------------------------------ |
| **Author** | Yuefeng Zhou (yuefengz@google.com)                                        |
|**Sponsors**| Alexandre Passos (apassos@google.com), Martin Wicke (wicke@google.com), Josh Levenberg  (joshl@google.com) |
|**Updated** | 2019-1-16                                                                 |
Summary: this RFC describes the design and interfaces for embeddings and partitioned variables in TF 2.0 based on Distribution Strategy. We propose to support embeddings and sharded layers with DistributionStrategy and Keras' layer API. We also …

RFC: Embedding and Partitioned Variables in TF 2.0 

---

rfcs/20190115-dense-attention.md

**The feedback phase will be open for 2 weeks until 2019-01-30**
| Status        | Proposed                                                                   |
:-------------- |:-------------------------------------------------------------------------- |
| **Author(s)** | Georgios Roumpos (roumposg@google.com)                                     |
| **Sponsors**  | Karmel Allison (karmel@google.com), Francois Chollet (fchollet@google.com) |
| **Updated**   | 2019-01-15                                                                 |
This RFC proposes adding a layer for attention in `tf.keras.layers` that works with CNN/DNN networks. 
Recently people have had success using the Attention mechanism in dense layers,
e.g. CNN+Attention or Transformer networks. `tf.keras.layers` is the …

RFC: Attention for Dense Networks on Keras

---

rfcs/20190117-tf-module.md

**This review is open for public comment until 2019-02-11**
| Status        | Accepted                                                          |
| :------------ | :---------------------------------------------------------------- |
| **Author(s)** | DeepMind: tomhennigan@google.com, mareynolds@google.com           |
|               | Google: agarwal@google.com, apassos@google.com, dberth@google.com |
| **Sponsor**   | apassos@google.com                                                |
| **Updated**   | 2019-01-16                                                        |
**Summary**
We propose a lightweight base class (`tf.Module`) for stateful containers in TensorFlow. This base class offers three main features:
-   **Naming** - variables and ops created inside modules are created within a …

RFC: Stateful Containers with tf.Module

---

rfcs/20180824-tf-print-v2.md

**Review period open until 2018-09-10**
Status        | Proposed
:------------ | :---------------------------------
**Author(s)** | Tomer Kaftan (Google)
**Sponsor**   | Asim Shankar (Google)
**Updated**   | 2018-08-24
A proposal for a new `tf.print` operator, as part of TF 2.0 development.
This doc proposes a new `tf.print` TensorFlow printing approach that is very
similar to the standard python `print` API whether or not executing eagerly. It
also provides long-requested functionality for both eager and session-based
execution, such as a more meaningful Tensor summarization, support for printing
nested data structures that contain tensors, and controllable logging levels.

RFC: New tf.print

---

rfcs/20180905-deprecate-collections.md

The feedback phase will be open for two weeks until 2018-09-20
| **Author(s)** | Rohan Jain (Google) |
| **Sponsor**   | Asim Shankar (Google)                 |
| **Updated**   | 2018-09-05                                           |
TF 2.0 gives us a great opportunity to clean up APIs that are not as desirable. The collections API, although it permits a compact coding style and is widely used, poses a fair amount of technical difficulties and challenges and so we'd like to get rid of it.
1.  **Eager execution:** There isn't a concept of a graph when executing eagerly and therefore no support for collections.
2.  **Graph mode:** Collections are …

RFC: Deprecate Collections

---

rfcs/20190225-tf-on-demand.md

*Comment period is open until 2019-03-13* 
| Status        | Proposed      |
| **Author(s)** | Gunhan Gulsoy (gunan@google.com), Hye Soo Yang (hyey@google.com) |
| **Sponsor**   | Gunhan Gulsoy (gunan@google.com)                |
| **Collaborators** | Christoph Goern (goern@redhat.com), Subin Modeel (smodeel@redhat.com)         |
| **Updated**   | 2019-02-25                                           |
This document proposes a system to build optimized binaries in the cloud and deliver the artifacts to users of TensorFlow. With this system, we aim to achieve the following:
*   Hide the complexity of the build system of TF from beginner and intermediate users.
*   Improve the out-of-the-box performance for users.
* …

RFC: TF on Demand Project

---

rfcs/20181116-saved-model.md

**Review period closes 2018-12-04**
| Status        | Accepted       |
| **Author(s)** | Allen Lavoie (allenl@google.com), André Susano Pinto (andresp@google.com), Arno Eigenwillig (arnoegw@google.com), Rohan Jain (rohanj@google.com) |
| **Sponsor**   | Karmel Allison (karmel@google.com) |
| **Updated**   | 2019-02-28                                           |
Objective: provide an API for serialization/deserialization in TF-2.0 that supports both serving and reuse use-cases.

RFC: SavedModel Save/Load in 2.x

---

rfcs/20190308-addons-proxy-maintainership.md

**Comment period ends 2019-04-08**
| **Author(s)** | Paige Bailey (webpaige@google.com), Sean Morgan (seanmorgan@outlook.com), Yan Facai (facai.yan@gmail.com) |
| **Sponsor**   | Karmel Allison (karmel@google.com)                 |
| **Updated**   | 2019-03-23                                         |
[TensorFlow Addons](https://github.com/tensorflow/addons) is a repository of contributions that conform to well-established API patterns, but implement new functionality not available in core TensorFlow. For TensorFlow Addons to support [code that is moved from `tf.contrib` to `addons`](https://github.com/tensorflow/community/blob/ef626896f30130dfc3b5e75126c94624b689a943/rfcs/20181214-m …

RFC: Sustainability of TensorFlow Addons

---

rfcs/20190208-pybind11.md

**The review period for this RFC will end on 2019-02-26**
| **Author**    | amitpatankar@google.com                              |
| **Sponsor**   | wicke@google.com, gunan@google.com, jkline@google.com|
| **Updated**   | 2019-02-09                                           |
[SWIG](http://www.swig.org/tutorial.html) is an interface compiler that connects code written in C++ with our Python API. Currently we are using SWIG across all of TensorFlow. We would like to deprecate SWIG and transition over to using pybind11. 
This document describes a system to improve:
1.  code readability
2.  build times
3.  binary size
4.  performance of the Python …

RFC: Replace SWIG with pybind11

---

rfcs/20190411-tensorboard-improved-plugin-ext.md

Comment period ends 2019-05-19
| **Author(s)** | Stephan Lee (Google), William Chargin (Google) |
| **Sponsor**   | Mani Varadarajan (Google)                 |
| **Updated**   | 2019-05-16                                           |
This RFC proposes a friction-free approach to enabling TensorBoard contributors to create and share TensorBoard plugins as installable extensions.
TensorBoard is composed of various plugins that show up as separate dashboards to users (e.g., scalars, graphs, hparams, histograms, etc.). Today. anyone can contribute a new plugin by forking TensorBoard, adding their plugin, and getting the PR merged. However, this can require a lengthy review to make sure …

RFC: TensorBoard - Improved Plugin Extensibility

---

rfcs/20190509-keras-saved-model.md

**Feedback period open until 2019-05-27**
| Status        | Accepted                                             |
| **Author(s)** | Kathy Wu (kathywu@google.com)                        |
| **Sponsor**   | Karmel (karmel@google.com)                           |
| **Updated**   | 2019-05-30                                           |
Add ability to (1) save a [TensorFlow SavedModel](https://www.tensorflow.org/alpha/guide/saved_model) from a Keras model and (2) load a Keras model from a SavedModel. This is a  standalone serialization format, which allows models with custom objects to be saved/loaded without having the original code (currently required by the HDF5 and JSON formats). 
**Goals:**
- Add SavedModel format …

RFC: Keras SavedModel saving/loading

---

20190425-keras-premade-models.md
rfcs/20190425-keras-premade-models.md

**Feedback period will be open until 2019-05-10**
| **Author(s)** | Zhenyu Tan (tanzheny@google.com)|
| **Sponsor**   | Francois Chollet (fchollet@google.com), Alexandre Passos (apassos@google.com) |
| **Updated**   | 2019-04-29                                           |
This document proposes several pre-made Keras models that would allow users to:
* build basic machine learning models easily
* compose them with other keras Layers
* replace [Canned Estimators](https://www.tensorflow.org/guide/premade_estimators) in TF 2.0.

RFC: Keras Pre-made Models

---

sigs/io/RELEASE.md

The releae process for SIG-IO has been changed, as whl files
are now generated automatically and pushed to Bintray first.
This PR captures changes in release process.
cc @tensorflow/sig-io-maintainers 

Update Release process for SIG-IO

---

rfcs/yyyymmdd-rfc-template.md

Start allocating each RFC a number, for ease of future reference, based on the pull request. This enables tracing the RFC back to its discussion in the GitHub PR. 
Further work: we can also go back and add these to pre-existing RFCs.

Add way to allocate numbers to RFCs

---

sigs/testing/faq.md

Update links to TensorFlow 2 course (on deeplearning.ai) since the old one returned a 404. Change `tensorflow.org/alpha` to `/beta`. Update the date.

Update links to TensorFlow 2 course, beta docs

---

sigs/jvm/rfcs/20190802-java-repositories.md

**Comment period is open through 2019-08-30**
| **Author**    | Karl Lessard (karl.lessard@gmail.com) |
| **Sponsor**   | James Ring (Google) |
| **Updated**   | 2019-08-02                                           |
Create new repositories under the `github.com/tensorflow` organization to host the code supported by SIG JVM, including the actual Java client found in TensorFlow core repository.

RFC: Java Repositories

---

rfcs/20190828-tfx-resolver.md

**Review will be open through 2019-09-12**
Status        | Proposed
:------------ | :--------------------------------------------
**Author(s)** | Ruoyu Liu (ruoyu@google.com)
**Sponsor**   | Konstantinos Katsiapis (katsiapis@google.com)
**Updated**   | 2019-08-28
This RFC proposes the design of Resolver, which serves as an optional plugin in TFX DSL to handle artifact resolution before a component execution. The following can be achieved with this design:
*   Enable artifact resolution across pipeline run boundaries
*   Make artifact resolution easy to customize directly through pipeline definition

RFC: TFX Resolver

---

rfcs/20190821-nodejs-saved-model.md

This RFC will be open for comment until Thursday, September 5th, 2019.
| **Author(s)** | kangyizhang@google.com |
| **Sponsor**   | smilkov@google.com, nsthorat@google.com, piyu@google.com, kreeger@google.com |
| **Updated**   | 2019-08-21                                           |
This project is aiming to enable native TF SavedModel execution in Node.js environment without conversion.
*   Implement an API to load and execute TF SavedModel in Node.js for inference, supporting both TF 1.x and 2.0.
*   Wrap the loaded SavedModel as a new subtype implementing tf.InferenceModel, so users could call default signatureDef or other signatureDefs with tag.
*   Enable the ability to inspect …

RFC: Native SavedModel execution in Node.js

---

sigs/io/RELEASE.md

Update Release process of SIG IO to use Dropbox
/cc @tensorflow/sig-io-maintainers 

Update Release process of SIG IO to use Dropbox

---

rfcs/20190501-tf-tensor-cord.md

**Comment period is open until 2019-05-15**
| **Author(s)** | Eugene Brevdo (ebrevdo@google.com) |
| **Sponsor**   | Alex Passos (apassos@google.com)                 |
| **Updated**   | 2019-05-01
This document proposes a new Variant object called TensorCord.  A TensorCord
contains a list of `absl::string_view` and release functors / tensor references; and
can be used to store references to other Tensors or other memory locations.  The
destructor of a TensorCord reduces the count on its referenced releasers; once
the reference count of a releaser reaches 0, it is executed.

RFC: TensorCord Variant Object

---

rfcs/20190816-tf-project-versioning.md

**Review period open until 2019-08-30**
| **Author(s)** | Edd Wilder-James (ewj@google.com), Martin Wicke (wicke@google.com) |
| **Sponsor**   | Kevin Haas (khaas@google.com)                 |
| **Updated**   | 2019-08-16                                           |
This document describes best practices for numbering versions of projects that form part of the TensorFlow suite of projects. This practice is required for dependent projects hosted under the [TensorFlow organization](https://github.com/tensorflow) on GitHub, and advisory for dependent projects hosted elsewhere.

RFC: Project versioning in the TensorFlow organization

---

sigs/io/RELEASE.md

Update SIG I/O release team

---

rfcs/20190612-mlir-dialect.md

**This proposal is open for review until 2019-06-27**
|Status        | Proposed                                  |
|:------------ | :-----------------------------------------|
|**Author(s)** | Mehdi Amini (aminim@google.com)           |
|              | Tatiana Schpeisman (shpeisman@google.com) |
|              | Chris Lattner (clattner@google.com)       |
|**Sponsor**   | Alexandre Passos (apassos@google.com)     |
|              | Jacques Pienaar (jpienaar@google.com)     |
|**Updated**   | 2019-06-10                                |
[MLIR](https://medium.com/tensorflow/mlir-a-new-intermediate-representation-and-compiler-framework-beba999ed18d) is the intermediate representation and compiler framework we are investing in to build the compiler infrastructure for TensorFlow. The …

RFC: MLIR Dialects for TensorFlow

---

sigs/addons/RELEASE.md

Closes https://github.com/tensorflow/addons/issues/856

[Addons] update release procedure

---

rfcs/20200113-tf-data-service.md

*Comment period is open till 1/27/2020.*
| Status        | Accepted                          |
| **RFC #**     | [195](https://github.com/tensorflow/community/pull/195) |
| **Author(s)** | Andrew Audibert (aaudibert@google.com) Rohan Jain (rohanj@google.com)       |
| **Sponsor**   | Jiri Simsa (jsimsa@google.com)                          |
| **Updated**   | 2019-01-30
Provide an API and implementation of a tf.data service which can process tf.data
datasets in a distributed manner. The service can be run outside the TensorFlow
cluster or be exported as a gRPC service by TensorFlow servers.
Goals:
-   Enable horizontal scaling of dataset computation to improve performance of
input-bound dataset pipelines.
- …

RFC: tf.data Service

---

rfcs/20200107-tf-data-snapshot.md

_Comment period is open till 1/20/2020._
| Status        | Accepted                                                |
| **RFC #**     | [193](https://github.com/tensorflow/community/pull/193) |
| **Author(s)** | Frank Chen (frankchn@google.com), Rohan Jain            |
|               | (rohanj@google.com)                                     |
| **Sponsor**   | Jiri Simsa (jsimsa@google.com)                          |
| **Updated**   | 2020-02-10                                              |
With ever faster accelerators available in Cloud and hyperparameter tuning
consuming larger chunks of accelerator time, TensorFlow users are increasingly
finding that they don’t have enough CPU resources to keep up with these …

RFC: tf.data Snapshot

---

rfcs/20200117-tfx-generic-trainer.md

**This RFC will be open for comment until Wednesday, Feb 19th, 2020.**
cc @karmel
| Status        | Proposed                                               |
| :------------ | :----------------------------------------------------- |
| **RFC #**      |  201 |
| **Author(s)** | Jiayi Zhao (jyzhao@google.com) |
| **Sponsor**   | Konstantinos Katsiapis (katsiapis@google.com), Zhitao Li (zhitaoli@google.com), Karmel Allison (karmel@google.com) |
| **Updated**   | 2020-01-17                                             |
Support any TensorFlow Training loop in TFX Trainer in addition to tf.estimator, primarily focused on native Keras model.
This doc will focus on native Keras support (without model_to_estimator) in TFX.
We propose changing the user facing API to be more generic so that users can …

RFC: TFX Generic Trainer / Native Keras Support

---

rfcs/20190802-model-garden-redesign.md

This RFC will be open for comment until Friday, August 16th, 2019.
|**RFC#**| 130|
| **Author(s)** | Jing Li (jingli@google.com), Hongkun Yu (hongkuny@google.com), Xiaodan Song (xiaodansong@google.com) |
| **Sponsor**   | Edd Wilder-James (ewj@google.com)                 |
| **Updated**   | 2019-08-02                                           |
This document presents a proposal to redesign TensorFlow official model garden.
We aim to provide a central and reliable place to contain popular examples,
state-of-the-art models and tutorials to demonstrate the best practice in TF2.0
and illustrate real-world use cases.

RFC: TensorFlow Official Model Garden Redesign

---

rfcs/20200211-tf-types.md

| Status        | Draft       |
| **RFC #**     | [https://github.com/tensorflow/community/pull/208](https://github.com/tensorflow/community/pull/https://github.com/tensorflow/community/pull/208) |
| **Author(s)** | Dan Moldovan (mdan@google.com) |
| **Sponsor**   | Gaurav Jain (gjn@google.com)                 |
| **Updated**   | 2020-02-19                                           |
This RFC proposes a new TensorFlow module and namespace (`tf.types`) dedicated to storing implementation-free type definitions, similar to C++ header files. This module has no other dependencies inside TensorFlow, so any other internal module can depend on it to ensure interoperability without the risk of creating circular dependencies. …

RFC: TensorFlow Canonical Type System

---

rfcs/20190430-tokenization-conventions.md

Seems like a copy&paste glitch broke the comment in the code block.

Fix typo in 20190430-tokenization-conventions.md.

---

sigs/micro/CHARTER.md

the micro folder was moved out of the experimental folder. this was not yet updated in the link.

Update dead link in charter.md

---

governance/cpp-style.md

This guide is a starting point for documenting Tensorflow C++ style, especially where it differs from general Google C++ style.
The goal of this PR is to reflect style rules *as they are today*, so that we can be on the same page about what the style rules are, and so that we have a basis from which to discuss potential changes to the style rules. This PR itself is not the right place to discuss changing the style rules (though if the content here does not reflect the current reality, by all means please comment!).

Add C++ style guide.

---

rfcs/20200520-tensor-float-32.md

This RFC will be open for comment until Wednesday, June 3rd, 2020.
| **RFC #**     | [247](https://github.com/tensorflow/community/pull/247) |
| **Author(s)** | Reed Wanderman-Milne (reedwm@google.com)             |
| **Sponsor**   | Sanjoy Das (sanjoy@google.com)                 |
| **Updated**   | 2020-05-20                                           |
Allow [TensorFloat-32](https://blogs.nvidia.com/blog/2020/05/14/tensorfloat-32-precision-format) to be used in TensorFlow to improve performance.

RFC: TensorFloat-32 support in TensorFlow

---

rfcs/20191212-keras-categorical-inputs.md

Only one minor change to split "IndexLookup" to "StringLookup" and "IntegerLookup". The rest is trivial.
But more importantly, add an official guide on how TF1 Estimator users with feature columns can convert their code into TF2 Keras users with KPL.

Update Keras categorical input design, mark it as complete.

---

rfcs/20200525-gelu-migration.md

Following the yet to be merged template from: https://github.com/tensorflow/community/pull/241
This is a bit overdue so wanted to start the discussion period. Linking PR:
https://github.com/tensorflow/tensorflow/pull/33945

RFC: Migrate gelu activation from Addons to Core

---

rfcs/20200616-keras-multihead-attention.md

| Status        | Proposed         |
| **RFC #**     | [260](https://github.com/tensorflow/community/pull/260) |
| **Author(s)** | Hongkun Yu (hongkuny@google.com), Mark Omernick (momernick@google.com)   |
| **Sponsor**   | Francois Chollet (fchollet@google.com)                  |
| **Updated**   | 2020-06-16                                              |
Introduce the MultiHeadAttention layer and EinsumDense layer to tf.keras.

RFC: Multihead Attention and EinsumDense on Keras

---

governance/api-reviews.md

We want to require all new public APIs to have publicly documented arguments and return values.

Policy to require public types for API

---

rfcs/20200824-e2e-text-preprocessing.md

| Status        | (Proposed)                                                            |
:-------------- |:----------------------------------------------------------------------|
| **RFC #**     | [283](https://github.com/tensorflow/community/pull/283)               |
| **Author(s)** | Terry Huang (Google), Arno Eigenwillig (Google), Chen Chen (Google)   |
| **Sponsor**   | Xiaodan Song(Google), Greg Billock (Google), Mark Omernick (Google)   |
| **Updated**   | 2020-08-24                                                            |
Introduce a new suite of text preprocessing APIs to empower the end-to-end transformation of text to model inputs in TensorFlow, expressive enough for pre-training and downstream tasks of Transformer Encoders such as BERT, ALBERT, XLNet, etc.

RFC: End-to-end text preprocessing with TF.Text

---

sigs/addons/RELEASE.md

Add missing step per https://github.com/tensorflow/addons/issues/2075

Update Addons Release.md

---

rfcs/20200916-sig-tf-js.md

| Status        | Proposed      |
| **RFC #**     | 289 |
| **Author(s)** | Ping Yu (piyu@google.com), Sandeep Gupta (sandeepngupta@google.com) |
| **Sponsor**   | Thea Lamkin (thealamkin@google.com)                  |
| **Updated**   | 2020-09-16                                           |
We propose to create a Tensorflow SIG to facilitate community-contributed components 
to tensorflow/tfjs. This document outlines the context goals, and engagement plan for 
the proposed Special Interest Group.

RFC: Creating SIG TF.js

---

rfcs/20200921-pickle-for-keras.md

Comment period is open until 10-13.
As per discussion in https://github.com/tensorflow/tensorflow/pull/39609#issuecomment-685869003
| **RFC #**     | [286](https://github.com/tensorflow/community/pull/286) |
| **Author(s)** | Adrian Garcia Badaracco ({firstname}at{firstname}gb.com), Scott Sievert (tf-rfc@stsievert.com)  |
| **Sponsor**   | Mihai Maruseac (mihaimaruseac@google.com)                 |
| **Updated**   | 2020-09-21                                           |
Implement support for Pickle, Python's serialization protocol within Keras.

RFC: Pickle Protocol for Keras

---

rfcs/20201012-tfx-tf-function-in-tft.md

This RFC will be open for comment until Friday, November 6th, 2020.
cc @jsimsa @zoyahav @katsiapis
| Status        | Proposed                                                |
| **RFC #**     | [308](https://github.com/tensorflow/community/pull/308)|
| **Author(s)** | Varshaa Naganathan (varshaan@google.com)                |
| **Sponsor**   | Konstantinos Katsiapis (katsiapis@google.com), Jiri Simsa (jsimsa@google.com), Zohar Yahav (zoy@google.com)    |
| **Updated**   | 2020-10-12                                              |
For tf.transform users who have TF 2 features enabled, tf.transform will
internally use tf.function to trace the user defined preprocessing function.
This is expected to work for the …

RFC: Supporting tf.function in tf.transform

---

rfcs/20201023-sig-models.md

This RFC will be open for comment until Wednesday, November 11st, 2020.
We propose to create a TensorFlow SIG Models.
| **RFC #**     |           314                                           |
| **Author(s)** | Jaeyoun Kim (jaeyounkim@google.com), Jing Li (jingli@google.com), Mike Liang (mliang@google.com), Shuangfeng Li (shuangfeng@google.com) |
| **Sponsor**   | Thea Lamkin (thealamkin@google.com)                  |
| **Updated**   | 2020-10-23                                           |
This group is for discussions and collaborations on enabling community
contributions to [TensorFlow Model Garden](https://github.com/tensorflow/models)
and …

RFC: Creating SIG Models

---

rfcs/20200804-configurable-filesystems.md

This RFC is a proposal to add two new methods to Filesystem API to expose handles to users for modifying tuning parameters of persistent storage access such as in-memory buffer sizes, open handles, number of threads and such. These parameters have hardcoded defaults for that works for most cases but not necessarily optimal under all circumstances. With this change users will be able to modify such parameters that developers chose to expose through configuration API.
| Status        | Proposed                                                                                      |
| :------------ | :-------------------------------------------------------------------------------------------- |
| **RFC #**     | [NNN](https://github.com/tensorflow/community/pull/NNN) (update when you have …

RFC:  Adding configurable Filesystems

---

sigs/recommenders/CHARTER.md

Create SIG Recommenders charter

---

sigs/io/RELEASE.md

This PR updates the release process for tensorflow/io,
replacing the Travis CI part with the new GitHub Actions process.
/cc @BryanCutler @terrytangyuan @vlasenkoalexey @dmitrievanthony 

Update the Release process for tensorflow/io

---

governance/api-reviews.md

Clarify how Python version compatibility is handled. This is mostly covered by testing, since we do run tests with the minimum version, but not entirely (as seen with 3.8 and async).

Add a note about Python versions

---

sigs/recommenders/CHARTER.md

Update contacts and adjust out-of-date wordings

Update SIG Recommener contacts

---

rfcs/20210302-sig-tfx-addons.md

_This RFC will be open for comments until March 16, 2021._
| **RFC #**     | [363](https://github.com/tensorflow/community/pull/363)|
| **Author(s)** | Robert Crowe (robertcrowe@google.com), Thea Lamkin (thealamkin@google.com) |
| **Sponsor**   | Zhitao Li (zhitaoli@google.com), Mihai Maruseac (mihaimaruseac@google.com) |
| **Updated**   | 2021-03-02                                           |
We propose to create SIG TFX-Addons to facilitate community contributions of community-supported software and tools which can be used with TFX to build a production ML solution. This RFC outlines the context, goals, and engagement plan for the proposed Special Interest Group.

RFC: Create SIG TFX-Addons

---

sigs/tensorboard/CHARTER.md

Gal is no longer part of the TensorBoard project at Google

Update contacts in TensorBoard community charter.

---

rfcs/20210119-determinism.md

Open for comment until 2/4/2021
:---------------|:-----------------------------------------------------|
| **Author(s)** | Pankaj Kanwar (Google), Reed Wanderman-Milne (Google), Duncan Riach (NVIDIA)|
| **Sponsor**   | Sanjoy Das (Google)                                |
Allow users to enable determinism behavior in TensorFlow. This means if the user runs a TensorFlow program multiple times, the model outputs and weights will be the same each time. Determinism will be supported on CPUs and GPUs.
To get deterministic behavior, users must do the following:
* Enable determinism using the API proposed in this doc
* Use same hardware every run
* Use the same software environment every run (OS, checkpoints, version of TF, …

RFC: Enhancing determinism in TF

---

rfcs/20210218-grpc-fail-fast-use-caller.md

The feedback phase will be open for two weeks until 2021-03-18
| Status        | Approved                                                |
| **RFC #**     | [355](https://github.com/tensorflow/community/pull/355) |
| **Author(s)** | Haoyu Zhang (haoyuzhang@google.com)                     |
| **Sponsor**   | Bramandia Ramadhana (bramandia@google.com)              |
| **Updated**   | 2021-03-04                                              |
We propose to set the default value of the `GRPC_FAIL_FAST` environment variable to `use_caller`. This change prevents TensorFlow distributed jobs from hanging indefinitely due to task failures, and allows users and TF libraries (e.g., distribution strategies) to handle the …

RFC: Setting GRPC_FAIL_FAST to use_caller by Default

---

governance/api-reviews.md

Fixes https://github.com/tensorflow/community/issues/280

Remove restricted link

---

rfcs/20210119-determinism.md

This updated list adds ops, fixes various issues, and sorts the ops lexicographically.

RFC: [determinism] Improve list of ops in

---

rfcs/20190722-tflite-training.md

Use respectful terms like "allowlist"

Use respectful terms like "allowlist"

---

governance/SIG-contributing-template.md

This is a Draft CONTRIBUTING.md template.
It is part of an effort to standardize some early access info for [Github community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) across the TensorFlow ecosystem repositories.

Add CONTRIBUTING.md template

---

rfcs/20210307-tfx-api-artifact-compat.md

This RFC will be open for comments until April 7, 2021
| Status        | Proposed                                                                                      |
| **RFC #**     | [API & Artifact Compatibility for TFX::OSS & Libraries.](https://github.com/tensorflow/community/pull/372)|
| **Author(s)** | Zhitao Li (zhitaoli@google.com), Jiayi Zhao (jyzhao@google.com), Zhuo Peng (zhuo@google.com)         |
| **Sponsor**   | Konstantinos Katsiapis (katsiapis@google.com), Zhitao Li (zhitaoli@google.com)                 |
| **Updated**   | 2021-03-21                                           |
Defining requirements and processes for TFX::OSS and related libraries to achieve
necessary API & Artifact compatibility. …

RFC: API & Artifact Compatibility for TFX OSS & Libraries

---

rfcs/20210504-kernel-extension-variable-ops.md

The RFC will be open for comment until Tuesday, May 18, 2021
| Status        | Proposed      |
| **RFC #**     | [387](https://github.com/tensorflow/community/pull/387)                                  |
| **Author(s)** | Kulin Seth (Apple), Charles Brissart (Apple) |
| **Sponsor**   | Saurabh Saksena (srbs@google.com)            |
| **Updated**   | 2021-05-04                                   |
The proposal extends the current [Kernel C API](https://github.com/tensorflow/community/blob/master/rfcs/20190814-kernel-and-op-registration.md) to enable plugin writers using Modular API to add support for :
* Optimizer operations like SGD, Adam etc.
* Variable updates like Assign, AssignUpdate

RFC: Kernel C API extension for Variable ops.

---

sigs/io/RELEASE.md

This PR updates the SIG-IO Release team list.
cc: @yongtang @mihaimaruseac

update the SIG-IO release team list

---

rfcs/20211116-tensorshape-bool.md

**This RFC will be open for comment until Friday, December 3rd, 2021.**
cc @rohan100jain @rainwoodman
| **Author(s)** | Bogdan Alexe (Google), Yu Feng (Google) |
| **Sponsor**   | Rohan Jain (Google)                 |
| **Updated**   | 2021-11-16                                           |
Fix inconsistencies in `TensorShape` evaluation to `bool`.

TensorShape Evaluation to Bool

---

rfcs/20191212-keras-categorical-inputs.md

The numeric columns for loop was adding encodings from the previous categorical columns loop. The line in question was removed.

Removed duplicate encode parch layers

---

rfcs/20201121-keras-model-fit-ps.md

**This RFC will be open for comment until Friday, December 7th, 2020.**
| Status        | Under review                                             |
:---------------|:-----------------------------------------------------|
| **RFC #** | 334                                                                 |
| **Author(s)** | Rick Chao, Tom O'Malley, Zhenyu Tan, Yuefeng Zhou (Google)                                  |
| **Sponsor**   | Francois Chollet, Priya Gupta (Google)                                |
| **Updated**   | 2020-11-21                                        |
*   Parameter server training support for Keras compile/fit style training API
*   Minimal code changes across usage with other strategies
*   Minimal performance implications

RFC: Distributed Keras training APIs with parameter servers

---

rfcs/20200810-tf-internal-api.md

Comment period is open until 08/25/2020.
| Status        | Proposed |
| **RFC #**     | [278](https://github.com/tensorflow/community/pull/278)|
| **Author(s)** | Qianli Zhu (scottzhu@google.com) |
| **Sponsor**   | Martin Wicke (wicke@google.com), Alex Passos (apassos@google.com)|
| **Updated**   | 2020-09-03                                          |
| **Intended audience**| tf-api-owners, tf-addons, keras-team, deepmind/sonnet|
Adding a new `__internal__` API namespace in TF to host APIs for framework building/testing, etc. The API namespace will serve as a whitelist for client libraries to gradually migrate off the usage tf private API symbol.
This design has been updated comparing to its original proposal. The …

RFC: tf.__internal__ API namespace.

---

rfcs/20200810-tf-internal-api.md

We decided to use tf.\_\_internal\_\_ to make sure the user side ready understand this is for private/internal usage only.

Fix the naming in the API name space.

---

governance/SIG-readme-template.md

This is a Draft `README.md` template. 
It is part of an effort to standardize some early access info for [Github community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) across the TensorFlow ecosystem repositories.

Add a standard README.md template

---

rfcs/20220620-tfx-modify-bulkinferrer.md

| Status        | Proposed                                                                                      |
:-------------- |:----------------------------------------------------------------------------------------------|
| **RFC #**     | [417](https://github.com/tensorflow/community/pull/417) |
| **Author(s)** | Abin Thomas (abin.thomas@blueyonder.com), Iain Stitt (iain.stitt@blueyonder.com)              |
| **Sponsor**   | Robert Crowe (robertcrowe@google.com)                                                         |
| **Updated**   | 2020-06-20                                                                                    |
Modify [BulkInferrer](https://github.com/tensorflow/tfx/tree/master/tfx/components/bulk_inferrer) TFX component.
Changes :-
* Store only a subset of …

RFC: Modify BulkInferrer TFX component

---

rfcs/20220713-sig-open-xla.md

| Status        | Accepted     |
| **RFC #**     | [419](https://github.com/tensorflow/community/pull/419)|
| **Author(s)** | Thea Lamkin (thealamkin@google.com), Mehdi Amini (aminim@google.com) |
| **Sponsor**   | Thea Lamkin (thealamkin@google.com)            |
| **Updated**   | 2022-07-13                                           |
We propose to create SIG OpenXLA to facilitate development of an open, state-of-art ML compiler, built collaboratively with ML hardware & framework developers, using the best of XLA & MLIR.
OpenXLA will be a community-driven and modular open source compiler. It will enable efficient lowering, optimization and deployment of ML models from most major frameworks to any hardware backend …

RFC: Establish SIG OpenXLA

---

rfcs/20220719-sig-federated

| Status        | Proposed     |
| **RFC #**     | 423 |
| **Author(s)** | Krzysztof Ostrowski (ostrowski@google.com|
| **Sponsor**   | Thea Lamkin (thealamkin@google.com)            |
| **Updated**   | 2022-07-19                                           |
[TensorFlow Federated (TFF)](http://tensorflow.org/federated) is an OSS platform based on TensorFlow for machine learning and other computations on decentralized data. TFF is [hosted on GitHub](https://github.com/tensorflow/federated) and available to OSS and industry contributors and potential [platform collaborators](https://github.com/tensorflow/federated/tree/main/docs/collaborations).
We would like to build and cultivate a center of gravity around TFF, where …

RFC: Create SIG Federated 

---

sigs/federated/CHARTER.md

Creates a new SIG named "federated" for collaborations around TensorFlow Federated (TFF), and adds the initial SIG charter (CHARTER.md).

Creates SIG "federated" and the SIG charter.

---

rfcs/20220610-saved-model-fingerprinting.md

Since there is now a need for a public API to read the fingerprint, I have added that revision to the RFC: https://github.com/tensorflow/community/pull/415

[SavedModel Fingerprinting] Amend RFC #415 to include public API.

---

rfcs/20230621-tf-api-deprecation.md

| **RFC #**     | [450](https://github.com/tensorflow/community/pull/450) |
| **Author(s)** | Ayush Jain (ayh@google.com)                          |
| **Sponsor**   | Rohan Jain (rohanj@google.com)                       |
| **Updated**   | 2023-06-21                                           |
This RFC will be open for comment until Friday, July 7th, 2023.
This proposal outlines an explicit policy for long-term code health by adding a process and mechanism for API / op deprecation and removal, specific to TensorFlow.
Because of TensorFlow’s position in the Google-internal, enterprise, and open-source ML development worlds, we take special care when deprecating or removing public …

[RFC] Adding an API deprecation mechanism for TensorFlow

---

rfcs/20230720-unbound-saved-model.md

This RFC will be open for comment until Friday, August 11th, 2023.
cc @k-w-w @petrychenko
| Status        | Implemented                                                                                  |
:-------------- |:-------------------------------------------------------------------------------------------- |
| **RFC #**     | [453](https://github.com/tensorflow/community/pull/453)  |
| **Author(s)** | Kathy Wu (<kathywu@google.com>), Adam Cogdell (<adamcogdell@google.com>)                     |
| **Sponsor**   | Ivan Petrychenko (<petrychenko@google.com>)                                                  |
| **Updated**   | 2023-07-24                                                                                   |
We are proposing a new format for `SavedModel` and a generic …

RFC: Unbound SavedModel
