CODEOWNERS

Add @perfinion and @angersson to SIG Build, and @goldiegadde to RFCs.

Update CODEOWNERS for SIG Build, RFCs

---

rfcs/20181026-tf-nightly.md

| Status        | Implemented                                             |
| **Author**    | amitpatankar@google.com 								  |
| **Sponsor**   | gunan@google.com                                        |
| **Updated**   | 2018-10-26                                              |
Plan a new process and protocol for how we build and distribute nightly binaries.

RFC: tf-nightly renovations

---

sigs/io/RELEASE.md

Happy to help with the future releases. 
cc: @martinwicke @ewilderj @mrry @yongtang @dmitrievanthony

Added myself to SIG IO release team

---

sigs/io/CHARTER.md

Per our discussion on mailing list, Edd created this Gitter room. Welcome to join!

Added link to Gitter room for SIG-IO

---

sigs/tensorboard/CHARTER.md

Adding Gal to the TensorBoard SIG charter.

Add Gal to TensorBoard charter

---

MEETINGS.md

Adding this so there is basic information about how to find the community calendar and get invited to meetings.

Initial signpost for community meetings

---

sigs/networking/CHARTER.md

I will leave my current company soon, so update my email.

Change contact email address

---

sigs/addons/CHARTER.md

Add Yan Facai as another project lead.

Update addons owners

---

rfcs/20190308-addons-proxy-maintainership.md

PR to update the maintainers of addons. I don't think we need to keep this constantly up to date but the prior listing was pretty incomplete and outdated.

Update addons maintainership RFC

---

sigs/swift/CHARTER.md

Create SIG Swift Charter

---

sigs/swift/CHARTER.md

PTAL @ewilderj @dynamicwebpaige

Fix typos in swift/CHARTER.md

---

sigs/addons/RELEASE.md

Add release documentation for SIG Addons

---

rfcs/20190904-tfx-generic-container-based-component.md

**Review will be open through 2019-10-9**
Status        | Proposed
:------------ | :-------
**Author(s)** | Ajay Gopinathan (<a href="mailto:ajaygopinathan@google.com">ajaygopinathan@google.com</a>), Hongye Sun (<a href="mailto:hongyes@google.com">hongyes@google.com</a>), Makoto Uchida (<a href="mailto:muchida@google.com">muchida@google.com</a>)
**Sponsor**   | Konstantinos Katsiapis (katsiapis@google.com)
**Updated**   | 2019-09-04
This document proposes a design to enable users to attach an arbitrary
containerized program as a component to a pipeline authored using the TFX DSL,
in a way that inter-operates with other components.
This RFC assumes some clarification on the TFX’s use of artifacts and metadata
as explained in [this section of TFX user …

RFC: TFX Generic Container-based Component

---

sigs/addons/RELEASE.md

Those are the files which must freeze tf version before release. cc @seanpmorgan

Addons: List all files which are related to tf version

---

rfcs/20190430-tokenization-conventions.md

**This review is open for public comment until 2019-05-15**
Status        | Accepted
:------------ | :-----------------------------------
**Author(s)** | Robby Neale (Google)
**Sponsor**   | Mark Omernick (Google), Greg Billock (Google)
**Updated**   | 2019-04-18
Establish a base Tokenizer class for TensorFlow tokenizers to extend, and create an initial set of tokenization offerings which implement this API.

RFC: Tokenization API & Initial Implementations

---

sigs/io/RELEASE.md

Additional details that need to be checked before release.

Update SIG IO R package release instruction

---

rfcs/yyyymmdd-rfc-template.md

Adding a link to Examples in the RFC template.

Adding a link to Examples

---

sigs/build/CHARTER.md

My username has changed and I didn't notice before that this was out of date.

Update @angersson to @angerson

---

sigs/addons/RELEASE.md

Continuing the process of simplifying the build/release.

[Addons] Updated release procedure

---

rfcs/20191212-keras-categorical-inputs.md

Finalize design reviews from https://github.com/tensorflow/community/pull/188

RFC: Keras categorical inputs

---

sigs/build/tensorflow-testing.md

Fixes [#37327](https://github.com/tensorflow/tensorflow/issues/37327). 
@gdequeiroz , @dynamicwebpaige,@alextp and @MarkDaoust  - Please review this one.

Fixed broken link for Bug & Performance issues

---

rfcs/20191127-pip-structure.md

This has already been implemented.  Updating the text with the link to the implementation.

Mark RFC as implemented

---

sigs/graphics/CHARTER.md

Fix markdown formatting in SIG Graphics charter

---

sigs/tf.js/CHARTER.md

Implements: TF RFC #289  https://github.com/tensorflow/community/pull/289

Create SIG TF.js & Add CHARTER.md

---

sigs/tf.js/CHARTER.md

Add mailing list & monthly meeting details

---

sigs/addons/CHARTER.md

Per discussion with Joana
cc @WindQAQ

Add SIG Lead for Addons

---

sigs/models/CHARTER.md

Create SIG Models charter

---

sigs/addons/CHARTER.md

Update addons sponsor

---

CODEOWNERS

Remove/Replace ex-Googlers in OWNERS

---

sigs/swift/CHARTER.md

Updating the contacts for the SIG.

Updating contacts for SIG

---

sigs/tf.js/CHARTER.md

Starting to get more involved in this one so adding name to list of names.

Adding name to Google folk for SIG

---

rfcs/20200916-sig-tf-js.md

Added myself for SIG and current projects.

Updates for my SIG

---

rfcs/20200901-tflite-builtin-code-extension.md

Add "RFC: Builtin code extension in TFLite".

RFC: Builtin code extension in TFLite

---

sigs/addons/CHARTER.md

In favor of #428
cc @theadactyl @bhack

Update SIG Addons Charter

---

rfcs/20230221-tf-distribution-api-dtensor.md

| Status        | Accepted         |
| **RFC #**     | [442](https://github.com/tensorflow/community/pull/442) |
| **Author(s)** | Yu Feng (feyu@google.com)                               |
|               | Bruce Fontaine (bfontain@google.com)                    |
|               | Yuefeng Zhou (yuefengz@google.com)                      |
|               | Scott Zhu (scottzhu@google.com)                         |
|               | Srujun Thanmay Gupta (srujun@google.com)                |
|               | Justin Szaday (twelve@google.com)                       |
|               | Samuel Lee (samuelslee@google.com)                      |
| **Sponsor**   | Yu Feng (feyu@google.com)                               |
| …

RFC: Distribution API and DTensor
